### ISSUE TITLE
trouble running the code

### ISSUE THREAD

**Issue by JiaheXu** [anniesch/single-life-rl#1]
Hi Annies, when I try cmd "python3 train.py use_discrim=True rl_pretraining=True q_weights=True online_steps=200000 env_name=pointmass", the terminal shows the following error message:
Error executing job with overrides: ['use_discrim=True', 'rl_pretraining=True', 'q_weights=True', 'online_steps=200000', 'env_name=pointmass']
Traceback (most recent call last):
  File "train.py", line 473, in main
    workspace.train(snapshot_dir)
  File "/home/jiahexu/learning-based_ws/single-life-rl/train.py", line 292, in train
    min_q, max_q = cur_buffer.load_buffer(f'{snapshot_dir}/', self.cfg.prior_buffer_size, self.cfg.env_name)
  File "/home/jiahexu/learning-based_ws/single-life-rl/simple_replay_buffer.py", line 168, in load_buffer
    self._index = np.load(f'{replay_buffer_dir}/index.npy').tolist()
  File "/home/jiahexu/anaconda3/envs/slrl/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/jiahexu/learning-based_ws/single-life-rl/data/offline/pointmass_buffer///index.npy'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Am I missing some files?

**Comment by anniesch** [comment]
Hi @JiaheXu, thanks for letting me know! Sorry, those npy files were missing, but I just added them. Does this fix the issue?

**Comment by JiaheXu** [comment]
Yep, but new error comes out...... 

Starting single episode
Resetting wiggly weight env
location -1.0498545741865284 -0.2733211992077832
| train | F: 1000 | S: 1000 | E: 803 | L: 1000 | R: 0.0000 | BS: 0 | FPS: 0.0000 | T: 235 days, 19:53:36
location -6.766585288030802 -2.1129478447973042
Error executing job with overrides: ['use_discrim=True', 'rl_pretraining=True', 'q_weights=True', 'online_steps=200000', 'env_name=pointmass']
Traceback (most recent call last):
  File "train.py", line 473, in main
    workspace.train(snapshot_dir)
  File "/home/jiahexu/learning-based_ws/single-life-rl/train.py", line 419, in train
    metrics = cur_agent.update(trans_tuple, self.global_step)
  File "/home/jiahexu/learning-based_ws/single-life-rl/agents.py", line 183, in update
    self.update_critic(obs, action, reward, discount, next_obs, step, not_done))
  File "/home/jiahexu/learning-based_ws/single-life-rl/agents.py", line 114, in update_critic
    self.critic_opt.step()
  File "/home/jiahexu/.local/lib/python3.8/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/jiahexu/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/jiahexu/.local/lib/python3.8/site-packages/torch/optim/adam.py", line 113, in step
    self._cuda_graph_capture_health_check()
  File "/home/jiahexu/.local/lib/python3.8/site-packages/torch/optim/optimizer.py", line 95, in _cuda_graph_capture_health_check
    and self.defaults["capturable"]
KeyError: 'capturable'

I installed the latest pytorch. Maybe you can upload a docker image of your system?

**Comment by anniesch** [comment]
Got it, here are the package versions that I used: https://pastebin.com/pg0BAb4a. You might need to install an earlier version of pytorch.
